server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot_oauth_server
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: ALWAYS
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
