server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:boot_oauth_server;DB_CLOSE_DELAY=-1 #jdbc:mysql://localhost:3306/boot_oauth_server
    username: root
    password: password
    driver-class-name: org.h2.Driver #com.mysql.cj.jdbc.Driver
    initialization-mode: ALWAYS
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-oauth


lms:
  oauth:
    issuer: http://lms.in:${server.port} #http://localhost:${server.port} -> changed hostname for localhost for development
    authorization_endpoint: http://lms.in:${server.port}/oauth/v1/authorize
    token_endpoint: http://lms.in:${server.port}/oauth/v1/token
    userinfo_endpoint: http://lms.in:${server.port}/v1/userinfo
    jwks_uri: http://lms.in:${server.port}/oauth/v1/certs
#    registration_endpoint: http://localhost:${server.port}
    token_endpoint_auth_methods_supported:
      - client_secret_basic
      - client_secret_post
    token_endpoint_auth_signing_alg_values_supported:
      - RS256
    scopes_supported:
      - openid
      - profile
      - email
    response_types_supported:
      - code
    grant_types_supported:
      - authorization_code
      - refresh_token
    subject_types_supported:
      - public
