server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot_oauth_server
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: ALWAYS
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true


lms:
  oauth:
    issuer: http://localhost:${server.port}
    authorization_endpoint: http://localhost:${server.port}/oauth/v1/authorize
    token_endpoint: http://localhost:${server.port}/oauth/v1/token
    userinfo_endpoint: http://localhost:${server.port}/v1/userinfo
    jwks_uri: http://localhost:${server.port}/oauth/v1/certs
#    registration_endpoint: http://localhost:${server.port}
    token_endpoint_auth_methods_supported:
      - client_secret_basic
      - client_secret_post
    token_endpoint_auth_signing_alg_values_supported:
      - RS256
    scopes_supported:
      - openid
      - profile
      - read.user.book
      - create.user.book
      - read.book
      - create.book
    response_types_supported:
      - code
    grant_types_supported:
      - authorization_code
      - refresh_token

